[theme]
primaryColor = "#667eea"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[client]
showErrorDetails = false
toolbarMode = "minimal"

[client]
showSidebarNavigation = false
toolbarMode = "minimal"

[ui]
hideTopBar = true
hideSidebarNav = true